modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="yuoenchants"
version="1.18.2-0.0.5"
displayName="YuoEnchants"
authors="yuo" #optional
description='''
更多附魔1.18.2版本。
'''
# Here's another dependency
[[dependencies.yuoenchants]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
